### ISSUE TITLE
Added Meta-Tag with no value fails in W3C validation

### ISSUE THREAD

**Issue by juergenweb** [pedroborges/meta-tags#3]
If a Meta tag with no value is added it outputs an incorrect Meta-Tag.
To prevent this it would be the best to add an if condition (check if value is present or not) before the output of the tag.

For example an empty Twitter image tag outputs the following:

`<meta name="twitter:image">`

This is not correct. To easy solve this problem it would be the best to check if the image value is present. If yes then output this meta tag with the present value, if not do not output this meta tag.

This is extremly useful if the values are generated dynamically. Otherwise it is always necessary to check it directly in the template.

Best regards

**Comment by pedroborges** [comment]
Thank you!
